### ISSUE TITLE
iQBit - what happened?

### ISSUE THREAD

**Issue by benfishbus** [imTHAI/unraid-templates#2]
I've been using your unraid template for iqbit for a few months, and it's been working fine until a couple days ago when I updated the container. The log looks completely wrong. It actually looks like a log that would belong to your qbittorrent+filebot container. More importantly, the port it's supposed to be serving iqbit on is not serving anything.

Can you see if the wrong image got pushed or something? I don't see any older image to roll back to on dockerhub.

**Comment by imTHAI** [comment]
Hello,
Fixed. I had a problem with a disk and had to restore some data. There was a typo in my restored json.

+ pull req on the project for a missing dependency (I fixed it locally).
